## Import Libraries

In [2]:
# Database
import sqlalchemy as sa

# Data Manipulation and Analysis
import pandas as pd
import numpy as np

## Connect to SQL Database

In [3]:
# url for project submission

url='postgresql://Test:bQNxVzJL4g6u@ep-noisy-flower-846766.us-east-2.aws.neon.tech/TravelTide'

# Create an engine and connect to database
engine = sa.create_engine(url)
connection = engine.connect().execution_options(isolation_level='AUTOCOMMIT')

# **Initial Data Exploration**



---

In [4]:
# Create query
query = '''
select *
from users
where sign_up_date>'2023-01-04'
order by sign_up_date desc
limit 100000
'''

pd.read_sql(query, con=connection)

,user_id,birthdate,gender,married,has_children,home_country,home_city,home_airport,home_airport_lat,home_airport_lon,sign_up_date
0,1019632,1960-11-02,M,True,False,usa,new york,JFK,40.640,-73.779,2023-07-20
1,1020889,2006-04-17,F,False,False,usa,memphis,MEM,35.042,-89.977,2023-07-20
2,1020888,1989-08-04,F,False,False,usa,detroit,DTW,42.212,-83.353,2023-07-20
3,1020887,1993-10-02,M,True,True,usa,san francisco,SFO,37.619,-122.375,2023-07-20
4,1020886,1977-11-24,M,False,False,usa,phoenix,LUF,33.535,-112.383,2023-07-20
...,...,...,...,...,...,...,...,...,...,...,...
99995,920931,1975-09-02,F,True,True,usa,houston,HOU,29.645,-95.279,2023-06-14
99996,920930,1991-03-14,F,False,False,usa,new york,JFK,40.640,-73.779,2023-06-14
99997,920929,1985-08-03,M,False,False,usa,oklahoma city,TIK,35.415,-97.386,2023-06-14
99998,920928,1981-02-22,M,False,False,usa,houston,EFD,29.607,-95.159,2023-06-14
99999,920927,2000-05-20,M,True,False,canada,windsor,YQG,42.276,-82.956,2023-06-14

In [5]:
# Create query
query = '''
with user_level as(
 select user_id,
 count(session_id)
 from sessions s
 group by user_id
 having count(session_id)>7
 ),
 joined_tables as(
select *
from sessions s
 left join users u
on s.user_id = u.user_id
left join hotels h
on s.trip_id = h.trip_id
left join flights f
on s.trip_id = f.trip_id
 join user_level ul
 on s.user_id =ul.user_id
 where session_start>='2023-01-04'
)
select *
from joined_tables
order by Random()
limit 1000
'''

pd.read_sql(query, con=connection)

,session_id,user_id,trip_id,session_start,session_end,flight_discount,hotel_discount,flight_discount_amount,hotel_discount_amount,flight_booked,...,return_flight_booked,departure_time,return_time,checked_bags,trip_airline,destination_airport_lat,destination_airport_lon,base_fare_usd,user_id,count
0,382726-6dbed64d48ed4801bd8f129e70caa7d7,382726,None,2023-01-14 17:51:00,2023-01-14 17:51:16,False,True,NaN,0.10,False,...,None,NaT,NaT,NaN,None,NaN,NaN,NaN,382726,8
1,46648-567f62e9dd044561a958f044986de79c,46648,None,2023-01-12 14:07:00,2023-01-12 14:08:13,True,False,0.25,NaN,False,...,None,NaT,NaT,NaN,None,NaN,NaN,NaN,46648,10
2,444766-0aae95c314da4b47a31e46aa13589477,444766,None,2023-03-12 17:07:00,2023-03-12 17:07:52,False,False,NaN,NaN,False,...,None,NaT,NaT,NaN,None,NaN,NaN,NaN,444766,9
3,44922-fc2ba1741af3497b9173a9525c578787,44922,None,2023-01-22 20:28:00,2023-01-22 20:29:09,False,False,NaN,NaN,False,...,None,NaT,NaT,NaN,None,NaN,NaN,NaN,44922,10
4,499162-475e0ff877434c038540cdeada4a0541,499162,None,2023-03-21 13:24:00,2023-03-21 13:24:45,False,False,NaN,NaN,False,...,None,NaT,NaT,NaN,None,NaN,NaN,NaN,499162,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,313134-7a67f16f379b40af8dc9556ef43cfea0,313134,313134-21f02851fc0f48fbbac41a64f5435cd8,2023-01-09 20:28:00,2023-01-09 20:32:46,False,False,NaN,NaN,True,...,True,2023-06-27 07:00:00,2023-07-12 07:00:00,1.0,United Airlines,33.942,-118.408,723.56,313134,8
996,105610-f40d4cc3912a4e13ac7d75ac8a13db8e,105610,105610-bc0bb356e5ee4ddd864d79b6823896d6,2023-03-08 01:16:00,2023-03-08 01:19:27,False,True,NaN,0.15,True,...,True,2023-03-16 10:00:00,2023-03-23 10:00:00,1.0,Air Canada,45.323,-75.669,1429.30,105610,8
997,70272-6a8785ca1bb24daf9513de2c4c50ad3a,70272,70272-fa6d00bdbfd04e55b279577b54ec21ed,2023-06-04 21:08:00,2023-06-04 21:09:59,False,True,NaN,0.15,False,...,None,NaT,NaT,NaN,None,NaN,NaN,NaN,70272,10
998,33774-e928d6c6487e4210972de0b82c0552e0,33774,None,2023-01-13 11:50:00,2023-01-13 11:53:47,False,True,NaN,0.15,False,...,None,NaT,NaT,NaN,None,NaN,NaN,NaN,33774,10
999,34085-2b43ae972747427c82123cb19d631116,34085,34085-59030bf0edd54dda93417bfbf3522f74,2023-02-21 12:50:00,2023-02-21 12:58:37,False,False,NaN,NaN,False,...,None,NaT,NaT,NaN,None,NaN,NaN,NaN,34085,13

In [6]:
# Create query
query = '''
select nights
from hotels
where nights<0
'''

pd.read_sql(query, con=connection)

       nights
0          -1
1          -1
2          -1
3          -1
4          -1
...       ...
12062      -1
12063      -1
12064      -1
12065      -1
12066      -1

[12067 rows x 1 columns]

In [7]:
# Create query
query = '''
SELECT *
FROM sessions s
WHERE trip_id IS NULL AND
page_clicks = 0
LIMIT 10
'''

pd.read_sql(query, con=connection)

,session_id,user_id,trip_id,session_start,session_end,flight_discount,hotel_discount,flight_discount_amount,hotel_discount_amount,flight_booked,hotel_booked,page_clicks,cancellation
0,79755-837f1ca301d34e99ba9eac935dd2b0aa,79755,None,2022-10-04 06:04:00,2022-10-04 06:04:01,False,False,None,NaN,False,False,0,False
1,375379-0da849f4e6ef4a3f98c1a8f39bbd83ac,375379,None,2022-11-13 20:24:00,2022-11-13 20:24:01,False,False,None,NaN,False,False,0,False
2,360703-795417791e704205b456b5e186dd0a02,360703,None,2022-12-08 21:11:00,2022-12-08 21:11:01,False,False,None,NaN,False,False,0,False
3,442716-40f57093a89b4a0fa0f81dc47418ece4,442716,None,2022-12-24 09:12:00,2022-12-24 09:12:01,False,False,None,NaN,False,False,0,False
4,3356-18e24403d0cf4e8b99ac664fb2fd2eec,3356,None,2021-05-30 17:34:00,2021-05-30 17:34:01,False,False,None,NaN,False,False,0,False
5,64172-d408f9ec10204cb996fdc7d2a51cd681,64172,None,2021-11-30 20:52:00,2021-11-30 20:52:01,False,False,None,NaN,False,False,0,False
6,499093-901839fd4f39449393928ccdb15e4cdb,499093,None,2023-01-16 20:11:00,2023-01-16 20:11:01,False,True,None,0.1,False,False,0,False

In [8]:
# Create query
query = '''
-- Session level full dataset
WITH user_level AS (
 SELECT user_id, COUNT(session_id)
FROM sessions s
GROUP BY user_id
HAVING COUNT(session_id) > 7 ),
joined_tables AS (
SELECT *,
 CASE WHEN check_out_time::date - check_in_time::date <1
 THEN 1
 ELSE check_out_time::date - check_in_time::date END as nights_new,
 CASE when rooms=0 THEN 1 ELSE rooms END as new_rooms
FROM sessions s
LEFT JOIN users u
ON s.user_id = u.user_id
LEFT JOIN hotels h
ON s.trip_id = h.trip_id
LEFT JOIN flights f
ON s.trip_id = f.trip_id
 JOIN user_level ul
 ON s.user_id=ul.user_id
WHERE session_start >= '2023-01-04')
SELECT *
FROM joined_tables
ORDER BY RANDOM ()
LIMIT 10000
'''

pd.read_sql(query, con=connection)

,session_id,user_id,trip_id,session_start,session_end,flight_discount,hotel_discount,flight_discount_amount,hotel_discount_amount,flight_booked,...,return_time,checked_bags,trip_airline,destination_airport_lat,destination_airport_lon,base_fare_usd,user_id,count,nights_new,new_rooms
0,2884-7125bd2635004916af1709cfeb060412,2884,2884-7c89bd74e1ea4dcaa710316540a8c518,2023-01-21 18:44:00,2023-01-21 18:48:35,False,False,NaN,NaN,True,...,2023-02-07 15:00:00,1.0,AirTran Airways,32.847,-96.852,414.62,2884,10,9.0,1.0
1,187910-79664cb201c6491f8b8c115d3b7bf3ad,187910,None,2023-01-12 19:21:00,2023-01-12 19:21:14,False,False,NaN,NaN,False,...,NaT,NaN,None,NaN,NaN,NaN,187910,11,NaN,NaN
2,168966-2565286e840743f8a73cd5b9e8f74b22,168966,168966-ac6ca1062978461ba325c764019225f9,2023-01-23 06:03:17,2023-01-23 08:03:17,True,True,NaN,NaN,True,...,2023-02-05 07:00:00,1.0,Delta Air Lines,40.640,-73.779,412.12,168966,8,5.0,1.0
3,37356-8224b309d0e74d3895be4a6010e7181b,37356,None,2023-01-15 08:37:00,2023-01-15 08:37:59,False,False,NaN,NaN,False,...,NaT,NaN,None,NaN,NaN,NaN,37356,10,NaN,NaN
4,24231-f2447fffc1e84ba38aa2d590206d476f,24231,24231-bfbd22ca75684465afc787e569346f6c,2023-01-27 17:20:00,2023-01-27 17:26:00,False,False,NaN,NaN,True,...,2023-02-07 12:00:00,0.0,Delta Air Lines,47.530,-122.302,636.23,24231,9,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,531339-861810eb252043609fbe7c2deefef614,531339,None,2023-04-04 16:27:00,2023-04-04 16:27:16,False,False,NaN,NaN,False,...,NaT,NaN,None,NaN,NaN,NaN,531339,9,NaN,NaN
9996,279385-a715fafe808f4b28bf197dbf5c3add22,279385,None,2023-01-23 07:57:00,2023-01-23 07:57:21,False,False,NaN,NaN,False,...,NaT,NaN,None,NaN,NaN,NaN,279385,10,NaN,NaN
9997,320839-426467760ba14ae48aa1d4bc44cccbd3,320839,None,2023-03-06 17:45:00,2023-03-06 17:47:11,False,True,NaN,0.2,False,...,NaT,NaN,None,NaN,NaN,NaN,320839,8,NaN,NaN
9998,129024-c5111128209f46ea9a135d4abb1cac07,129024,129024-d8f027cc40264f8ea297d156449cc776,2023-04-01 22:15:00,2023-04-01 22:18:06,False,False,NaN,NaN,True,...,2023-04-10 10:00:00,1.0,Southwest Airlines,42.364,-71.005,734.77,129024,8,1.0,1.0
9999,286073-e69950ae333c4c7d93c8fc82670507d6,286073,286073-b9ddd2244f5b437cb283e3b2640c772f,2023-06-13 22:19:00,2023-06-13 22:20:21,False,False,NaN,NaN,True,...,2023-06-21 10:00:00,0.0,Air France,39.175,-76.668,351.78,286073,8,NaN,NaN

In [9]:
# Create query
query = '''
select
count( home_country)
from users
group by home_country
limit 1000
'''

pd.read_sql(query, con=connection)

    count
0  172572
1  848354

In [10]:
# Create query
query = '''
--What is the distribution of the user's birth year? Do you spot any irregularity there? What is special about birth year 2006? How would you calculate the age based on birth date
SELECT
   EXTRACT(YEAR FROM birthdate) AS birth_year,
   COUNT(*) AS user_count
FROM users
GROUP BY birth_year
ORDER BY birth_year;
'''

pd.read_sql(query, con=connection)

    birth_year  user_count
0       1931.0           1
1       1932.0           5
2       1933.0           8
3       1934.0          24
4       1935.0          33
..         ...         ...
71      2002.0       11063
72      2003.0        9575
73      2004.0        8619
74      2005.0        7497
75      2006.0       43360

[76 rows x 2 columns]

In [11]:
# Create query
query = '''
WITH gender_count AS (
 SELECT gender, COUNT(gender) AS gender_count
 FROM users
 GROUP BY gender
),
totals AS (
 SELECT COUNT(*) AS total_count
 FROM users
)
SELECT gender,
ROUND((gender_count::numeric/total_count),2)*100
FROM gender_count
CROSS JOIN totals;
'''

pd.read_sql(query, con=connection)

  gender  ?column?
0      F      44.0
1      M      55.0
2      O       1.0

In [12]:
# Create query
query = '''
select
f.trip_id,
h.trip_id,
case when f.trip_id=h.trip_id then 'same' else 'different'
end as trip_id_check
from flights f
join hotels h
on f.trip_id= h.trip_id
group by f.trip_id,h.trip_id
order by trip_id_check desc
limit 20000
'''

pd.read_sql(query, con=connection)

,trip_id,trip_id,trip_id_check
0,0-4660ff6465694177915a89aadedf81cc,0-4660ff6465694177915a89aadedf81cc,same
1,0-f866480914464318806e02de349732fb,0-f866480914464318806e02de349732fb,same
2,1-240dcec347d74794a42f89db57252550,1-240dcec347d74794a42f89db57252550,same
3,1-f35a49334eaa473aa993bde2c8f670ec,1-f35a49334eaa473aa993bde2c8f670ec,same
4,10-88d8253c524242be81e56383a40d764f,10-88d8253c524242be81e56383a40d764f,same
...,...,...,...
19995,105027-b42f45650d194f318b8a190cd3d71a3a,105027-b42f45650d194f318b8a190cd3d71a3a,same
19996,105027-cb57f546ad424370a996d76fb34bd4e8,105027-cb57f546ad424370a996d76fb34bd4e8,same
19997,105028-1e8a34d865ea4af2849a45f2509e4391,105028-1e8a34d865ea4af2849a45f2509e4391,same
19998,105028-850fa17d45554700b6726464d5706296,105028-850fa17d45554700b6726464d5706296,same
19999,105028-ef787418eb8549c9ba85af0d80ece289,105028-ef787418eb8549c9ba85af0d80ece289,same

In [13]:
# Create query
query = '''
--Travel frequency,anddays for married users with children
select
u.user_id,
u.home_country,
count(f.trip_id)as total_flights,
 SUM(EXTRACT(DAY FROM (f.return_time - f.departure_time))) AS travel_days
   from users u
   join sessions s
   on u.user_id = s.user_id
   join flights f
   on s.trip_id = f.trip_id
 where u.married = True And u.has_children = true
  group by u.user_id,u.home_country
   order by total_flights desc;
'''

pd.read_sql(query, con=connection)

        user_id home_country  total_flights  travel_days
0         72793          usa             10         61.0
1         13076          usa             10         40.0
2        170995          usa             10         35.0
3          7709          usa             10         36.0
4         16410       canada              9         29.0
...         ...          ...            ...          ...
131537   914088          usa              1          3.0
131538   914098          usa              1         16.0
131539   914103          usa              1          6.0
131540   914107          usa              1          NaN
131541   914119       canada              1         15.0

[131542 rows x 4 columns]

In [14]:
query = '''
SELECT
 'hotel_and_flight' AS trip_type,
 h.trip_id,
 h.check_out_time,
 f.return_time,
 EXTRACT(EPOCH FROM (f.return_time - h.check_out_time))/3600.0 AS hours_check_out_to_return,
 COUNT(*) OVER() AS count_inconsistent_time_sequences,
 MAX(EXTRACT(EPOCH FROM (f.return_time - h.check_out_time))/3600.0) OVER() AS min_negative_time_gap,
 AVG(EXTRACT(EPOCH FROM (f.return_time - h.check_out_time))/3600.0) OVER() AS avg_negative_time_gap,
 MIN(EXTRACT(EPOCH FROM (f.return_time - h.check_out_time))/3600.0) OVER() AS max_negative_time_gap
FROM hotels h
JOIN flights f ON h.trip_id = f.trip_id
WHERE
 f.return_time < h.check_out_time
LIMIT 10
'''

pd.read_sql(query, con=connection)

,trip_type,trip_id,check_out_time,return_time,hours_check_out_to_return,count_inconsistent_time_sequences,min_negative_time_gap,avg_negative_time_gap,max_negative_time_gap
0,hotel_and_flight,182974-c4533748ed33425287630dba89f8b62c,2022-09-05 11:00:00,2022-09-05 07:00:00,-4.0,430702,-1.0,-2.764192,-4.0
1,hotel_and_flight,185379-e3f7789a706e409cb8e0ff4df2c78d69,2022-08-31 11:00:00,2022-08-31 07:00:00,-4.0,430702,-1.0,-2.764192,-4.0
2,hotel_and_flight,187418-a40dc85e7d8048cc83d191e8a00489c2,2022-09-04 11:00:00,2022-09-04 08:00:00,-3.0,430702,-1.0,-2.764192,-4.0
3,hotel_and_flight,187476-1543a14f7a3e45cbada9404582975f05,2022-09-10 11:00:00,2022-09-10 08:00:00,-3.0,430702,-1.0,-2.764192,-4.0
4,hotel_and_flight,188063-b31c319dc9d348c39f8b5f9277639bd9,2022-09-03 11:00:00,2022-09-03 10:00:00,-1.0,430702,-1.0,-2.764192,-4.0
5,hotel_and_flight,189239-6671b0f273594d26888b1885299dfa91,2022-08-31 11:00:00,2022-08-31 10:00:00,-1.0,430702,-1.0,-2.764192,-4.0
6,hotel_and_flight,190719-04b27f58df38493b9af92b726a844a0b,2022-09-04 11:00:00,2022-09-04 07:00:00,-4.0,430702,-1.0,-2.764192,-4.0
7,hotel_and_flight,191711-802ae753e59e4e40b25250286688fa82,2022-09-04 11:00:00,2022-09-04 07:00:00,-4.0,430702,-1.0,-2.764192,-4.0
8,hotel_and_flight,192742-5f22a37e3f544491abf1b63db66b73e9,2022-09-03 11:00:00,2022-09-03 09:00:00,-2.0,430702,-1.0,-2.764192,-4.0
9,hotel_and_flight,193622-2250204c5c9941d79f80502db36ff9e2,2022-09-06 11:00:00,2022-09-06 09:00:00,-2.0,430702,-1.0,-2.764192,-4.0

In [15]:
query = '''
SELECT u.user_id,
AVG(haversine_distance(
       u.home_airport_lat,
       u.home_airport_lon,
       f.destination_airport_lat,
       f.destination_airport_lon
   )) AS distance_km
FROM users u
JOIN sessions s
ON u.user_id=s.user_id
JOIN flights f
ON f.trip_id=s.trip_id
GROUP BY u.user_id
LIMIT 10
'''

pd.read_sql(query, con=connection)

   user_id   distance_km
0        0   1694.413385
1        1  12208.887772
2        2   2078.961742
3        3   2364.292586
4        4   8908.830044
5        5   2805.393720
6        6   3317.129108
7        7   5448.631659
8        8   2832.412139
9        9   1433.235624

In [16]:
query = '''
WITH joined_tables AS (
   SELECT
       s.user_id AS u_id,
       s.session_id,
       s.trip_id,
       u.*,
       h.check_in_time,
       h.check_out_time,
       h.rooms,
       f.departure_time,
       f.return_time,
       f.checked_bags,
       f.destination_airport_lat,
       f.destination_airport_lon,
       CASE
           WHEN h.check_out_time::date - h.check_in_time::date < 1 THEN 1
           ELSE h.check_out_time::date - h.check_in_time::date
       END AS nights_new,
       CASE
           WHEN h.rooms = 0 THEN 1
           ELSE h.rooms
       END AS new_rooms,
       (hotel_per_room_usd *
        CASE WHEN h.check_out_time::date - h.check_in_time::date < 1 THEN 1
             ELSE h.check_out_time::date - h.check_in_time::date
        END
       ) AS amount_spent_hotel
   FROM sessions s
   LEFT JOIN users u ON s.user_id = u.user_id
   LEFT JOIN hotels h ON s.trip_id = h.trip_id
   LEFT JOIN flights f ON s.trip_id = f.trip_id
   WHERE s.session_start >= '2023-01-04'
),
user_level AS (
   SELECT u_id AS ul_id
   FROM joined_tables
   GROUP BY u_id
   HAVING COUNT(session_id) > 7
),
trip_metrics AS (
   SELECT
       s.user_id AS u_id,
       COUNT(DISTINCT s.trip_id) AS trips_frequency,
       Round(Avg(jt.nights_new)) AS avg_nights,
       Round(Avg(f.checked_bags)) AS avg_bags,
       Round(Avg(f.seats)) as avg_seats,
       Round(Avg(f.base_fare_usd),2)as amount_spent_flight,
                         ROUND(SUM(jt.amount_spent_hotel), 2) AS total_amount_spent_hotel,
       Round(AVG(EXTRACT(EPOCH FROM (f.return_time - f.departure_time)) / 86400)) AS average_trip_length_days,
       Round(AVG(haversine_distance(
           u.home_airport_lat,
           u.home_airport_lon,
           f.destination_airport_lat,
           f.destination_airport_lon
       ))::numeric,2) AS distance_km
   FROM sessions s
   JOIN flights f ON f.trip_id = s.trip_id
   JOIN users u ON s.user_id = u.user_id
   JOIN joined_tables jt ON jt.u_id = s.user_id
   GROUP BY s.user_id
),
session_metrics AS (
   SELECT
       user_id AS us_id,
       COUNT(DISTINCT session_id) AS total_sessions,
       SUM(page_clicks) AS clicks_per_session,
       ROUND(
           COUNT(*) FILTER (WHERE cancellation = TRUE)::DECIMAL / COUNT(*) * 100, 2
       ) AS cancellation_rate_percentage
   FROM sessions s
   GROUP BY user_id
),
user_metrics AS (
   SELECT
       ul.ul_id,
       COUNT(DISTINCT jt.session_id) AS num_sessions,
       jt.gender,
       jt.has_children,
       jt.married,
                         tm.total_amount_spent_hotel,
       CASE
           WHEN EXTRACT(YEAR FROM AGE('2023-07-28', jt.birthdate)) < 18 THEN 'under 18'
           WHEN EXTRACT(YEAR FROM AGE('2023-07-28', jt.birthdate)) < 25 THEN '18-25'
           WHEN EXTRACT(YEAR FROM AGE('2023-07-28', jt.birthdate)) < 35 THEN '25-35'
           WHEN EXTRACT(YEAR FROM AGE('2023-07-28', jt.birthdate)) < 45 THEN '35-45'
           WHEN EXTRACT(YEAR FROM AGE('2023-07-28', jt.birthdate)) < 55 THEN '45-55'
           WHEN EXTRACT(YEAR FROM AGE('2023-07-28', jt.birthdate)) < 65 THEN '55-65'
           ELSE '65+'
       END AS user_age,
       jt.home_country,
       jt.home_city,
       jt.home_airport,
       tm.trips_frequency,
       tm.avg_nights,
       tm.avg_bags,
       tm.average_trip_length_days,
       tm.distance_km,
       sm.total_sessions,
       sm.clicks_per_session,
       tm.avg_seats,
       tm.amount_spent_flight,
              tm.total_amount_spent_hotel,
       sm.cancellation_rate_percentage
   FROM joined_tables jt
   JOIN user_level ul ON jt.u_id = ul.ul_id
   LEFT JOIN trip_metrics tm ON tm.u_id = jt.u_id
   LEFT JOIN session_metrics sm ON sm.us_id = jt.u_id
 group by
 ul.ul_id,
 jt.gender,
       jt.has_children,
       jt.married,
       jt.birthdate,
       jt.home_country,
       jt.home_city,
       jt.home_airport,
       tm.trips_frequency,
       tm.avg_nights,
       tm.avg_bags,
       tm.average_trip_length_days,
       tm.distance_km,
       sm.total_sessions,
       sm.clicks_per_session,
       sm.cancellation_rate_percentage,
       tm.avg_seats,
       tm.amount_spent_flight,
       tm.total_amount_spent_hotel
 )
 select *
 from user_metrics;
'''

pd.read_sql(query, con=connection)

,ul_id,num_sessions,gender,has_children,married,total_amount_spent_hotel,user_age,home_country,home_city,home_airport,...,avg_nights,avg_bags,average_trip_length_days,distance_km,total_sessions,clicks_per_session,avg_seats,amount_spent_flight,total_amount_spent_hotel,cancellation_rate_percentage
0,23557,8,F,False,True,6492.0,55-65,usa,new york,LGA,...,10.0,1.0,7.0,2611.42,12,185,1.0,448.32,6492.0,8.33
1,94883,8,F,False,True,540.0,45-55,usa,kansas city,MCI,...,1.0,1.0,4.0,5303.67,12,100,2.0,1784.95,540.0,0.00
2,101486,8,F,True,True,6928.0,45-55,usa,tacoma,TCM,...,5.0,2.0,9.0,2401.20,13,340,3.0,1498.57,6928.0,7.69
3,101961,8,F,False,True,16788.0,35-45,usa,boston,BOS,...,4.0,1.0,4.0,1806.41,12,218,1.0,321.53,16788.0,0.00
4,106907,8,F,True,True,8514.0,35-45,usa,miami,TNT,...,11.0,4.0,13.0,9226.58,14,368,4.0,9323.21,8514.0,7.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5993,792549,8,F,False,False,720.0,45-55,usa,kansas city,MCI,...,5.0,1.0,3.0,1459.17,8,114,1.0,259.79,720.0,0.00
5994,796032,8,F,False,True,6620.0,45-55,canada,winnipeg,YAV,...,5.0,1.0,7.0,4763.57,8,148,2.0,1305.41,6620.0,12.50
5995,801660,8,F,True,True,3243.0,45-55,canada,toronto,YKZ,...,2.0,0.0,3.0,710.55,8,115,1.0,136.65,3243.0,0.00
5996,811077,8,F,True,True,994.0,35-45,usa,knoxville,TYS,...,7.0,0.0,8.0,3223.16,8,105,1.0,579.79,994.0,0.00
5997,844489,8,M,True,False,NaN,18-25,usa,el paso,BIF,...,NaN,NaN,NaN,NaN,8,99,NaN,NaN,NaN,0.00